<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7cc02988fc2e03e2c57f8c320c94aaba
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7cc02988fc2e03e2c57f8c320c94aaba::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7cc02988fc2e03e2c57f8c320c94aaba::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
